### ISSUE TITLE
[Bug][Linux][0.0.6] Visual Bug with already configured buttons not showing at server launch

### ISSUE THREAD

**Issue by thefinaldegree** [rnayabed/streampi_server#16]
OS: Ubuntu 20.04
Stream Pi Server: 0.0.6
Stream Pi Client: Android 0.0.6

Visual bug when launching:
 - Server will show the default 5x3 button set and be blank
 - Android app will show the same 5x3, but any buttons configured in that space will show up

The server will occasionally fix itself after you change the `Action Size` in the settings to force it to 'refresh' the buttons (I've been changing from 80 to 81, then back again), which doesn't always work to fix it but it will fix the Android app to show all of the buttons.
Any configured button still works when pressed (so long as it's not working as described in #15 ).

Please let me know if you need any further information and I'll do my best to provide.

**Comment by thefinaldegree** [comment]
After a bit of testing, I've found that I can force the server to refresh itself and show the correct buttons by letting the android app go into the background (by pressing the 'home' key in android), waiting for it to time out, then opening the android app and when it reconnects the server will show all the buttons again.

**Comment by rnayabed** [comment]
@thefinaldegree This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
