### ISSUE TITLE
New Application limitation - Linux

### ISSUE THREAD

**Issue by Necrot1c** [rnayabed/streampi_server#17]
Noticed the following limitation when adding an application to "Launch App" this is forced to search for .exe files. 
When running on Linux (in my case Arch with KDE) it is only displaying folders and exe files. Also allow the application path to be typed rather than have to browse to it

It would also be nice to remove the requirement for an icon and where missing display a default icon.

**Comment by Necrot1c** [comment]
When you are able to add the path to an application the following error is received:
```
launch_app::/usr/bin/konsole::action_145461::df
'launch_app'
Running "/usr/bin/konsole"
java.io.IOException: Cannot run program ""/usr/bin/konsole"": error=2, No such file or directory
```
An improvement on this apart from the issue above, is to allow this to be a command rather than just launching the application. For example, 
` xdotool search --class zoom key --window %@ Alt+A `

The above will send the key combination to a specific application, in this example Zoom.

**Comment by rnayabed** [comment]
@Necrot1c this repository has been shifted and moved to a better place. 

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
