### ISSUE TITLE
Number of tiles on server and client do not match

### ISSUE THREAD

**Issue by Necrot1c** [rnayabed/streampi_server#18]
The number of tiles on the server and client do not match. This is a fresh install of 0.0.6. The client is Raspbery Pi 3 B+ with a 1024x600 touch screen. The server is running on Arch.

Just noticed the bottom of the Pi screen is cut off, but there is an extra row at the bottom and an extra column on the right.

This would also be nice to be customisable with the number of rows and columns.

![image](https://user-images.githubusercontent.com/66018435/108074291-f2f13f00-7060-11eb-83a8-d2eb5b550594.png)

**Comment by rnayabed** [comment]
@Necrot1c this repository has been shifted and moved to a better place. 

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
