### ISSUE TITLE
Streampi Server Launch will only let me launch an EXE

### ISSUE THREAD

**Issue by 0lzi** [rnayabed/streampi_server#2]
![image](https://user-images.githubusercontent.com/4409144/78461974-a8bfd300-76c5-11ea-993e-4bed022c4f20.png)

Im running the server on my computer for test but plan to move to a Pi, but can only run EXE files for Launch App, when i would like to run a command to launch a linux application.

**Comment by dubbadhar** [comment]
Will try this asap on a linux machine and get back to you

**Comment by Tekkharibo** [comment]
> Will try this asap on a linux machine and get back to you

I think if you try to remove filter on launchAppConfig.java at line 305 or add an if with OS detection like this [https://mkyong.com/java/how-to-detect-os-in-java-systemgetpropertyosname/](https://mkyong.com/java/how-to-detect-os-in-java-systemgetpropertyosname/) and remove filter if is on linux

**Comment by dubbadhar** [comment]
ok noted. will add support for this in 1.0

**Comment by rnayabed** [comment]
@0lzi  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
