### ISSUE TITLE
Stuck on "Getting Things Ready..." message

### ISSUE THREAD

**Issue by dpertierra** [rnayabed/streampi_server#3]
![image](https://user-images.githubusercontent.com/17021695/81882471-361a0100-9569-11ea-909c-c6a9b79bd00e.png)
I have already tried with both versions 0.0.5 and 0.0.6
I get the connected message in both my terminal and android phone 
![image](https://user-images.githubusercontent.com/17021695/81882560-6cf01700-9569-11ea-88bc-7ecae4ffff3d.png)
I'm using port 1024 but have already tried port 1420 and I get the same behaviour

I'm running the Server in Pop_! OS 20.04
I'm running the client on a OnePlus 6 with Android 10

**Comment by dubbadhar** [comment]
You have to use the same version of client and server, also could you send over your device logcat?

**Comment by rnayabed** [comment]
@dpertierra  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
