### ISSUE TITLE
Desktop file for KDE Plasma

### ISSUE THREAD

**Issue by rolodoom** [rnayabed/streampi_server#4]
Maybe some instructions on "how to create" or include a *.desktop file for the server.sh file can be useful. On Plasma I don't enjoy the idea of double clicking an *.sh file and executing it. 

Besides, the use of a *.desktop file with an icon would be a nice feature, I'm a average guy / linux user but couldn't do it :(  something about the sh calling the java script, but couldn't figured it out.

Really good software and initiative, hope you keep doing it!!

**Comment by dubbadhar** [comment]
Yep. These will be added in 0.0.7

**Comment by rnayabed** [comment]
@rolodoom  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
