### ISSUE TITLE
[Feature request] Multi-Action

### ISSUE THREAD

**Issue by 0lzi** [rnayabed/streampi_server#5]
would like to see a multi action section where you can string multiple actions together similar to the actual stream deck.

This would allow some cool transitions and effect's in OBS.

I can see drop-down to select the action then a panel for details then a plus sign to add another action.

would also need to implement a delay action so you can add a delay between actions.

**Comment by dubbadhar** [comment]
Yes, coming in 0.0.7

**Comment by rnayabed** [comment]
@0lzi  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
