### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by chazp246** [rnayabed/streampi_server#6]
Hello,
i have problem with win server. I set it up and it shows that server is running on xxx port and x.x.x.x ip address. The problem is when i run netstat there is nothing on that port. My friend tried this and he was succesfull with netsat. I downloaded server.zip many times but server port never in netstat. It have not shown any type of error.
I want to use it with my phone (Xiaomi MI 8 Lite). This is why i have to use 0.0.6..
I have win10 home edition.

Thanks for help.

BTW i love your work.

**Comment by dubbadhar** [comment]
Are your phone and pc connected to the same exact network?

**Comment by chazp246** [comment]
Yes. The problem is that server is not running. I cant see it in netstat. My pc i connected by ethernet and my mobile is connected by wifi, but it is the same network. The problem is with server not starting. app says server running on xxx.xxx.xxx.xxx and port1420(tried multiple ports), but i am unable to see it in netstat. soo it propably means that server is not running

**Comment by 0lzi** [comment]
may be worth killing the java process and restarting it, also have you checked Windows firewall ?

**Comment by rnayabed** [comment]
@0lzi @chazp246  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
