### ISSUE TITLE
OBS Scenes causing connection to close.

### ISSUE THREAD

**Issue by thatguypotter** [rnayabed/streampi_server#7]
I am having an issue setting scenes for OBS studio. I can set up transitions and start/stop stream without issue. But when attempting to "set scene" or "set source visibility" the connection is closed and I am given the error `Connection closed: 1009 - Text message size [170851] exceeds maximum size [65536]`
OBS logs simply indicate that the client disconnected `[obs-websocket] client [::ffff:127.0.0.1]:38464 disconnected`
I have the server installed on manjaro and client installed on debian bullseye.

**Comment by dubbadhar** [comment]
This is weird, is the server itself throwing any error in the console?

**Comment by thatguypotter** [comment]
No errors at the time of disconnection. It gives me the connection closed notification in the console and the connection stays down until I return to streampi server and retry my connection to OBS. However when the server starts stderr outputs,
 `Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
2020-06-13 06:59:34.212:INFO::Thread-3: Logging initialized @-1ms to org.eclipse.jetty.util.log.StdErrLog`
I just realized I'm using the Alpha 0.0.5 build. I'll try it with 0.0.6 later today and see if I can replicate this.

**Comment by dubbadhar** [comment]
yes, please let us know if you can reproduce the same issue with 0.0.6

**Comment by marcmagus** [comment]
I am having this exact problem with 0.0.6
Arch Linux, obs-websocket-git pulled today, AUR streampi-server 0.0.6-1

OBS log with websocket debug logging just shows:

> 12:55:46 PM.384: [obs-websocket] Request >> '{"request-type":"GetSceneList",
> "message-id":"13"}'
> 12:55:46 PM.600: [obs-websocket] Response << '{
> 12:55:46 PM.600:     "current-scene": "Ending",
> 12:55:46 PM.600:     "message-id": "13",
> ...
> 12:55:46 PM.600:             "sources": [
> 12:55:46 PM.600:                 {
> 12:55:46 PM.600: 
> 12:55:46 PM.633: [obs-websocket] client 127.0.0.1:34646 disconnected

(Yes, it's cut off at that line, presumably the 65535 mark)

**Comment by dubbadhar** [comment]
will be fixed in upcoming release

**Comment by rnayabed** [comment]
fixed
