### ISSUE TITLE
[Feature request] Support for F13 to F24 Keys

### ISSUE THREAD

**Issue by Uro1** [rnayabed/streampi_server#8]
Hi, would it be possible to add support for the F13 through F24 keys?

I use these keys for macros since they are not physical keys, due to this applications do not have default keybinds which utilise the F13-F24 keys, making them macro safe for binding to.

Using them in the StreamPi Server app as a System>Hotkey results with them being set as 'Undefined' and not working as expected.

For reference they are defined in the USB HID spec's Usage tables on page 56 within this document - https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf

Cheers

**Comment by dubbadhar** [comment]
yes this will come in the next release

**Comment by RyanJField** [comment]
On this issue, it would be nice to be able to use the {enter} key as a hot key currently it just confirms the key binding

**Comment by dubbadhar** [comment]
Noted, @RyanJField !

**Comment by rnayabed** [comment]
@RyanJField  This issue has been fixed, Stream-Pi was rewritten and has been moved

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
